# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='listoforder',
            unique_together=set([('id_order', 'id_product')]),
        ),
    ]
