# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0002_auto_20160727_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listoforder',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='listoforder',
            old_name='id_product',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id_category',
            new_name='category',
        ),
        migrations.AlterUniqueTogether(
            name='listoforder',
            unique_together=set([('order', 'product')]),
        ),
    ]
