# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0009_auto_20160801_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='None', upload_to='products_photo/'),
        ),
    ]
