# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0010_auto_20160802_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='login',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
