# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tea', '0011_auto_20160803_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listoforder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
